version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
      - test-1.13
      - test-1.12
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/ssh-vault/ssh-vault
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -vendor-only
      - run: go test -race -v
  test-1.13:
    <<: *test-template
    docker:
      - image: circleci/golang:1.13
  test-1.10:
    <<: *test-template
    docker:
      - image: circleci/golang:1.12
